/*
 * Created on 2020-10-04 ( Time 22:37:05 )
 * Generated by Telosys Tools Generator ( version 3.1.2 )
 */
package it.csi.idf.idfapi.business.be.vincolo.api.impl;

import java.math.BigDecimal;
import java.util.List;

import javax.ws.rs.Consumes;
import javax.ws.rs.DELETE;
import javax.ws.rs.GET;
import javax.ws.rs.POST;
import javax.ws.rs.PUT;
import javax.ws.rs.Path;
import javax.ws.rs.PathParam;
import javax.ws.rs.Produces;
import javax.ws.rs.core.MediaType;
import javax.ws.rs.core.Response;
import javax.ws.rs.core.Response.Status;

import org.springframework.beans.factory.annotation.Autowired;

import it.csi.idf.idfapi.business.be.vincolo.api.IdfCnfSkOkVincIdroApi;
import it.csi.idf.idfapi.business.be.vincolo.pojo.IdfCnfSkOkVincIdro;
import it.csi.idf.idfapi.business.be.vincolo.service.IdfCnfSkOkVincIdroService;
import it.csi.idf.idfapi.util.SpringSupportedResource;
/**
 * JAXRS Jersey controller for 'IdfCnfSkOkVincIdro'ApiImpl management.
 */
@Path("/idfCnfSkOkVincIdro")
public class IdfCnfSkOkVincIdroApiImpl extends SpringSupportedResource implements  IdfCnfSkOkVincIdroApi{
	
	@Autowired
	private IdfCnfSkOkVincIdroService idfCnfSkOkVincIdroService ;

	/**
	 * Constructor
	 */
	public IdfCnfSkOkVincIdroApiImpl() {
		super();
		logger.info("Constructor.");
	}

	/**
	 * Get all idfCnfSkOkVincIdro entities.
	 * @return list with all entities found
	 */
	@Override
	@GET
	@Produces({MediaType.APPLICATION_JSON})
	public List<IdfCnfSkOkVincIdro> findAll() {
		logger.info("findAll()...");
		return idfCnfSkOkVincIdroService.findAll();
	}

	/**
	 * Retrieves a idfCnfSkOkVincIdro using the given id.
	 * @param idIntervento idIntervento
	 * @return 200 + body if found, 404 if not found 
	 */
	@Override
	@GET
	@Path("{idIntervento}")
	@Produces({MediaType.APPLICATION_JSON})
	public Response findById(@PathParam("idIntervento") BigDecimal idIntervento) {
		logger.info("findById("+idIntervento+")...");
		IdfCnfSkOkVincIdro record = idfCnfSkOkVincIdroService.findById(idIntervento);
		if ( record != null ) {
			return Response.ok(record).build();
		}
		else {
			return Response.status(Status.NOT_FOUND).build();
		}
	}

	/**
	 * Creates a new idfCnfSkOkVincIdro.
	 * @param idfCnfSkOkVincIdro idfCnfSkOkVincIdro
	 * @return 201 with body if created, 409 conflict if duplicate key 
	 */	
	@Override
	@POST
	@Consumes({MediaType.APPLICATION_JSON})
	@Produces({MediaType.APPLICATION_JSON})
	public Response create(IdfCnfSkOkVincIdro idfCnfSkOkVincIdro) {
		logger.info("create()...");
		if ( idfCnfSkOkVincIdroService.exists(idfCnfSkOkVincIdro) ) {
			logger.info("create() : already exists -> conflict");
			return Response.status(Status.CONFLICT).build();
		}
		else {
			logger.info("create() : doesn't exist -> create");
			IdfCnfSkOkVincIdro record = idfCnfSkOkVincIdroService.create(idfCnfSkOkVincIdro);
			return Response.status(Status.CREATED).entity(record).build();
		}
	}

//------------------------------------------------------------
	/**
	 * Updates the idfCnfSkOkVincIdro identified by the given id
	 * @param idfCnfSkOkVincIdro idfCnfSkOkVincIdro entity
	 * @param idIntervento idIntervento 
	 * @return 200 if found and updated, 404 if not found 
	 */	
	@Override
	@PUT
	@Path("{idIntervento}")
	@Consumes({MediaType.APPLICATION_JSON})
	@Produces({MediaType.APPLICATION_JSON})
	// public IdfCnfSkOkVincIdro update(IdfCnfSkOkVincIdro idfCnfSkOkVincIdro, @PathParam("idIntervento") BigDecimal idIntervento) {
	public Response update(IdfCnfSkOkVincIdro idfCnfSkOkVincIdro, @PathParam("idIntervento") BigDecimal idIntervento) {
		logger.info("update()...");
		// force the id (use the id provided by the URL)
		idfCnfSkOkVincIdro.setIdIntervento( idIntervento );
		boolean updated = idfCnfSkOkVincIdroService.update(idfCnfSkOkVincIdro);
		if ( updated ) {
			// Actually updated (found and updated) => 200 OK
			return Response.status(Status.OK).build();
		}
		else {
			// Not updated with no error => 404 not found
			return Response.status(Status.NOT_FOUND).build();
		}
	}

	/**
	 * Save (create or update) the given idfCnfSkOkVincIdro.
	 * @param idfCnfSkOkVincIdro idfCnfSkOkVincIdro entity
	 * @return 200 if found and updated, 201 if not found and created
	 */	
	@Override
	@PUT
	@Consumes({MediaType.APPLICATION_JSON})
	@Produces({MediaType.APPLICATION_JSON})
	public Response save(IdfCnfSkOkVincIdro idfCnfSkOkVincIdro) {
		logger.info("save()...");
		Status status = Status.OK ; // 200 OK
		if ( ! idfCnfSkOkVincIdroService.exists(idfCnfSkOkVincIdro) ) {
			status = Status.CREATED ; // 201 CREATED
		}
		IdfCnfSkOkVincIdro record = idfCnfSkOkVincIdroService.create(idfCnfSkOkVincIdro);
		// Response ( code 200 or 201 )
		return Response.status(status).entity(record).build();
	}


//------------------------------------------------------------
	/**
	 * Delete a idfCnfSkOkVincIdro.
	 * @param idIntervento idIntervento
	 */
	@Override
	@DELETE
	@Path("{idIntervento}")
	//@Consumes({MediaType.APPLICATION_JSON})
	// public void delete(@PathParam("idIntervento") BigDecimal idIntervento) {
	public Response delete(@PathParam("idIntervento") BigDecimal idIntervento) {
		logger.info("delete("+idIntervento+")...");
		// idfCnfSkOkVincIdroService.deleteById(idIntervento);
		boolean deleted = idfCnfSkOkVincIdroService.deleteById(idIntervento);
		if ( deleted ) {
			// Actually deleted (found and deleted) => 204 "No Content" because no body in the response 
			return Response.status(Status.NO_CONTENT).build();
		}
		else {
			// Not deleted with no error => 404 "Not found"
			return Response.status(Status.NOT_FOUND).build();
		}
}

	

}
