/*!
 * SPDX-FileCopyrightText: (C) Copyright 2023 Regione Piemonte
 * 
 * SPDX-License-Identifier: EUPL-1.2
 */
export enum TipoIstanzaEnum {

  DICHIARAZIONE_SOSTITUTIVA = 'DICHIARAZIONE SOSTITUTIVA',
  COMUNICAZIONE = 'COMUNICAZIONE',
  AUTORIZZAZIONE = 'AUTORIZZAZIONE',
  VINCOLO_AUTORIZZAZIONE_REGIONALE = 'VINCOLO AUTORIZZAZIONE REGIONALE',
  VINCOLO_AUTORIZZAZIONE_COMUNALE = 'VINCOLO AUTORIZZAZIONE COMUNALE'

}

