/*
 * Created on 2020-10-04 ( Time 22:37:06 )
 * Generated by Telosys Tools Generator ( version 3.1.2 )
 */
package it.csi.idf.idfapi.business.be.vincolo.api;

import java.math.BigDecimal;
import java.util.List;

import javax.ws.rs.Consumes;
import javax.ws.rs.DELETE;
import javax.ws.rs.GET;
import javax.ws.rs.POST;
import javax.ws.rs.PUT;
import javax.ws.rs.Path;
import javax.ws.rs.PathParam;
import javax.ws.rs.Produces;
import javax.ws.rs.core.MediaType;
import javax.ws.rs.core.Response;

import it.csi.idf.idfapi.business.be.vincolo.pojo.IdfRIntervincidroGoverno;

/**
 * JAXRS Jersey controller for 'IdfRIntervincidroGoverno'Api management.
 */
@Path("/idfRIntervincidroGoverno")
public interface IdfRIntervincidroGovernoApi {
	
	/**
	 * Get all idfRIntervincidroGoverno entities.
	 * @return list with all entities found
	 */
	@GET
	@Produces({MediaType.APPLICATION_JSON})
	public List<IdfRIntervincidroGoverno> findAll() ;

	/**
	 * Retrieves a idfRIntervincidroGoverno using the given id.
	 * @param idIntervento idIntervento
	 * @param idGoverno idGoverno
	 * @return 200 + body if found, 404 if not found 
	 */
	@GET
	@Path("{idIntervento}/{idGoverno}")
	@Produces({MediaType.APPLICATION_JSON})
	public Response findById(@PathParam("idIntervento") BigDecimal idIntervento, @PathParam("idGoverno") Integer idGoverno) ;
	/**
	 * Creates a new idfRIntervincidroGoverno.
	 * @param idfRIntervincidroGoverno idfRIntervincidroGoverno
	 * @return 201 with body if created, 409 conflict if duplicate key 
	 */	
	@POST
	@Consumes({MediaType.APPLICATION_JSON})
	@Produces({MediaType.APPLICATION_JSON})
	public Response create(IdfRIntervincidroGoverno idfRIntervincidroGoverno) ;

//------------------------------------------------------------
	
	/**
	 * Updates the idfRIntervincidroGoverno identified by the given id
	 * @param idfRIntervincidroGoverno idfRIntervincidroGoverno entity
	 * @param idIntervento idIntervento 
	 * @param idGoverno idGoverno 
	 * @return 200 if found and updated, 404 if not found 
	 */	
	@PUT
	@Path("{idIntervento}/{idGoverno}")
	@Consumes({MediaType.APPLICATION_JSON})
	@Produces({MediaType.APPLICATION_JSON})
	// public IdfRIntervincidroGoverno update(IdfRIntervincidroGoverno idfRIntervincidroGoverno, @PathParam("idIntervento") BigDecimal idIntervento, @PathParam("idGoverno") Integer idGoverno) {
	public Response update(IdfRIntervincidroGoverno idfRIntervincidroGoverno, @PathParam("idIntervento") BigDecimal idIntervento, @PathParam("idGoverno") Integer idGoverno); 
		// force the id (use the id provided by the URL)
		// idfRIntervincidroGoverno.setIdIntervento( idIntervento );
		// idfRIntervincidroGoverno.setIdGoverno( idGoverno );
		
	/**
	 * Save (create or update) the given idfRIntervincidroGoverno.
	 * @param idfRIntervincidroGoverno idfRIntervincidroGoverno entity
	 * @return 200 if found and updated, 201 if not found and created
	 */	
	@PUT
	@Consumes({MediaType.APPLICATION_JSON})
	@Produces({MediaType.APPLICATION_JSON})
	public Response save(IdfRIntervincidroGoverno idfRIntervincidroGoverno) ;

//------------------------------------------------------------
	/**
	 * Delete a idfRIntervincidroGoverno.
	 * @param idIntervento idIntervento
	 * @param idGoverno idGoverno
	 */
	@DELETE
	@Path("{idIntervento}/{idGoverno}")
	//@Consumes({MediaType.APPLICATION_JSON})
	// public void delete(@PathParam("idIntervento") BigDecimal idIntervento, @PathParam("idGoverno") Integer idGoverno) {
	public Response delete(@PathParam("idIntervento") BigDecimal idIntervento, @PathParam("idGoverno") Integer idGoverno) ;
		// idfRIntervincidroGovernoService.deleteById(idIntervento, idGoverno);
		

	

}
