/*
 * Created on 2020-10-04 ( Time 22:37:06 )
 * Generated by Telosys Tools Generator ( version 3.1.2 )
 */
package it.csi.idf.idfapi.business.be.vincolo.api;

import java.math.BigDecimal;
import java.util.List;

import javax.ws.rs.Consumes;
import javax.ws.rs.DELETE;
import javax.ws.rs.GET;
import javax.ws.rs.POST;
import javax.ws.rs.PUT;
import javax.ws.rs.Path;
import javax.ws.rs.PathParam;
import javax.ws.rs.Produces;
import javax.ws.rs.core.MediaType;
import javax.ws.rs.core.Response;

import it.csi.idf.idfapi.business.be.vincolo.pojo.IdfTIstanzaForest;

/**
 * JAXRS Jersey controller for 'IdfTIstanzaForest'Api management.
 */
@Path("/idfTIstanzaForest")
public interface IdfTIstanzaForestApi {
	
	/**
	 * Get all idfTIstanzaForest entities.
	 * @return list with all entities found
	 */
	@GET
	@Produces({MediaType.APPLICATION_JSON})
	public List<IdfTIstanzaForest> findAll() ;

	/**
	 * Retrieves a idfTIstanzaForest using the given id.
	 * @param idIstanzaIntervento idIstanzaIntervento
	 * @return 200 + body if found, 404 if not found 
	 */
	@GET
	@Path("{idIstanzaIntervento}")
	@Produces({MediaType.APPLICATION_JSON})
	public Response findById(@PathParam("idIstanzaIntervento") BigDecimal idIstanzaIntervento) ;
	/**
	 * Creates a new idfTIstanzaForest.
	 * @param idfTIstanzaForest idfTIstanzaForest
	 * @return 201 with body if created, 409 conflict if duplicate key 
	 */	
	@POST
	@Consumes({MediaType.APPLICATION_JSON})
	@Produces({MediaType.APPLICATION_JSON})
	public Response create(IdfTIstanzaForest idfTIstanzaForest) ;

//------------------------------------------------------------
	
	/**
	 * Updates the idfTIstanzaForest identified by the given id
	 * @param idfTIstanzaForest idfTIstanzaForest entity
	 * @param idIstanzaIntervento idIstanzaIntervento 
	 * @return 200 if found and updated, 404 if not found 
	 */	
	@PUT
	@Path("{idIstanzaIntervento}")
	@Consumes({MediaType.APPLICATION_JSON})
	@Produces({MediaType.APPLICATION_JSON})
	// public IdfTIstanzaForest update(IdfTIstanzaForest idfTIstanzaForest, @PathParam("idIstanzaIntervento") BigDecimal idIstanzaIntervento) {
	public Response update(IdfTIstanzaForest idfTIstanzaForest, @PathParam("idIstanzaIntervento") BigDecimal idIstanzaIntervento); 
		// force the id (use the id provided by the URL)
		// idfTIstanzaForest.setIdIstanzaIntervento( idIstanzaIntervento );
		
	/**
	 * Save (create or update) the given idfTIstanzaForest.
	 * @param idfTIstanzaForest idfTIstanzaForest entity
	 * @return 200 if found and updated, 201 if not found and created
	 */	
	@PUT
	@Consumes({MediaType.APPLICATION_JSON})
	@Produces({MediaType.APPLICATION_JSON})
	public Response save(IdfTIstanzaForest idfTIstanzaForest) ;

//------------------------------------------------------------
	/**
	 * Delete a idfTIstanzaForest.
	 * @param idIstanzaIntervento idIstanzaIntervento
	 */
	@DELETE
	@Path("{idIstanzaIntervento}")
	//@Consumes({MediaType.APPLICATION_JSON})
	// public void delete(@PathParam("idIstanzaIntervento") BigDecimal idIstanzaIntervento) {
	public Response delete(@PathParam("idIstanzaIntervento") BigDecimal idIstanzaIntervento) ;
		// idfTIstanzaForestService.deleteById(idIstanzaIntervento);
		


}
