/*
 * Created on 2020-10-04 ( Time 22:37:07 )
 * Generated by Telosys Tools Generator ( version 3.1.2 )
 */
package it.csi.idf.idfapi.business.be.vincolo.api;

import java.util.List;

import javax.ws.rs.Consumes;
import javax.ws.rs.DELETE;
import javax.ws.rs.GET;
import javax.ws.rs.POST;
import javax.ws.rs.PUT;
import javax.ws.rs.Path;
import javax.ws.rs.PathParam;
import javax.ws.rs.Produces;
import javax.ws.rs.core.MediaType;
import javax.ws.rs.core.Response;

import it.csi.idf.idfapi.business.be.vincolo.pojo.IdfTSoggetto;

/**
 * JAXRS Jersey controller for 'IdfTSoggetto'Api management.
 */
@Path("/idfTSoggetto")
public interface IdfTSoggettoApi {
	
	/**
	 * Get all idfTSoggetto entities.
	 * @return list with all entities found
	 */
	@GET
	@Produces({MediaType.APPLICATION_JSON})
	public List<IdfTSoggetto> findAll() ;

	/**
	 * Retrieves a idfTSoggetto using the given id.
	 * @param idSoggetto idSoggetto
	 * @return 200 + body if found, 404 if not found 
	 */
	@GET
	@Path("{idSoggetto}")
	@Produces({MediaType.APPLICATION_JSON})
	public Response findById(@PathParam("idSoggetto") Integer idSoggetto) ;
	/**
	 * Creates a new idfTSoggetto.
	 * @param idfTSoggetto idfTSoggetto
	 * @return 201 with body if created, 409 conflict if duplicate key 
	 */	
	@POST
	@Consumes({MediaType.APPLICATION_JSON})
	@Produces({MediaType.APPLICATION_JSON})
	public Response create(IdfTSoggetto idfTSoggetto) ;

//------------------------------------------------------------
	
	/**
	 * Updates the idfTSoggetto identified by the given id
	 * @param idfTSoggetto idfTSoggetto entity
	 * @param idSoggetto idSoggetto 
	 * @return 200 if found and updated, 404 if not found 
	 */	
	@PUT
	@Path("{idSoggetto}")
	@Consumes({MediaType.APPLICATION_JSON})
	@Produces({MediaType.APPLICATION_JSON})
	// public IdfTSoggetto update(IdfTSoggetto idfTSoggetto, @PathParam("idSoggetto") Integer idSoggetto) {
	public Response update(IdfTSoggetto idfTSoggetto, @PathParam("idSoggetto") Integer idSoggetto); 
		// force the id (use the id provided by the URL)
		// idfTSoggetto.setIdSoggetto( idSoggetto );
		
	/**
	 * Save (create or update) the given idfTSoggetto.
	 * @param idfTSoggetto idfTSoggetto entity
	 * @return 200 if found and updated, 201 if not found and created
	 */	
	@PUT
	@Consumes({MediaType.APPLICATION_JSON})
	@Produces({MediaType.APPLICATION_JSON})
	public Response save(IdfTSoggetto idfTSoggetto) ;

//------------------------------------------------------------
	/**
	 * Delete a idfTSoggetto.
	 * @param idSoggetto idSoggetto
	 */
	@DELETE
	@Path("{idSoggetto}")
	//@Consumes({MediaType.APPLICATION_JSON})
	// public void delete(@PathParam("idSoggetto") Integer idSoggetto) {
	public Response delete(@PathParam("idSoggetto") Integer idSoggetto) ;
		// idfTSoggettoService.deleteById(idSoggetto);
		


}
