/*!
 * SPDX-FileCopyrightText: (C) Copyright 2023 Regione Piemonte
 * 
 * SPDX-License-Identifier: EUPL-1.2
 */
export enum TipoAllegatoEnum {
  COMUNICAZIONE_DI_TAGLIO_IN_BOSCO_AUTOG = 'COMUNICAZIONE_DI_TAGLIO_IN_BOSCO_AUTOG',
	RICHIESTA_DI_AUTORIZZAZIONE_DI_TAGLIO_IN_BOSCO_AUTOG = 'RICHIESTA_DI_AUTORIZZAZIONE_DI_TAGLIO_IN_BOSCO_AUTOG',

  COMUNICAZIONE_DI_TAGLIO_IN_BOSCO_DIGIT = 'COMUNICAZIONE_DI_TAGLIO_IN_BOSCO_DIGIT',
	RICHIESTA_DI_AUTORIZZAZIONE_DI_TAGLIO_IN_BOSCO_DIGIT = 'RICHIESTA_DI_AUTORIZZAZIONE_DI_TAGLIO_IN_BOSCO_DIGIT',
  DICHIARAZIONE_DREL = 'DICHIARAZIONE_DREL'
}

/*
COMUNICAZIONE_DI_TAGLIO_IN_BOSCO_DIGIT(25),
RICHIESTA_DI_AUTORIZZAZIONE_DI_TAGLIO_IN_BOSCO_DIGIT(26),
COMUNICAZIONE_DI_TAGLIO_IN_BOSCO_AUTOG(36),
RICHIESTA_DI_AUTORIZZAZIONE_DI_TAGLIO_IN_BOSCO_AUTOG(37),
SCANSIONE_DOC_IDENTITA(38);

*/
